monolith:
  - ./*

decks:
  - ./decksite/*
  - ./decksite/**/*

logsite:
  - ./logsite/*
  - ./logsite/**/*

discord bot:
  - ./discordbot/*
  - ./discordbot/**/*

magic:
  - ./magic/*
  - ./magic/**/*

shared:
  - ./shared/*
  - ./shared/**/*
  - ./shared_web/*
  - ./shared_web/**/*

prices:
  - ./price_grabber/*
  - ./price_grabber/**/*

rotation:
  - ./rotation/*
  - ./rotation/**/*

maintenance:
  - ./maintenance/*
  - ./maintenance/**/*

tests:
  - ./**/*_test.py
