queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint


pull_request_rules:
  - name: automatic merge dependency updates
    conditions:
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint
      - author~=(pyup-bot|dependabot)
      - -files~=^(!?.github/workflows/)
    actions:
      merge:
        method: rebase
      delete_head_branch: {}
  - name: automatic merge for master when CI passes and approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint
      - base=master
    actions:
      queue:
        name: default
        method: rebase
  - name: automatic merge for master when CI passes and trusted comitter
    conditions:
      - author=@PennyDreadfulMTG/automerge
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint
      - base=master
    actions:
      queue:
        name: default
        method: merge
