language: python
branches:
  except:
    - staging.tmp
    - trying.tmp
python:
  - "3.6"
cache: pip
services:
  - mysql
env:
  - mysql_user=root magic_database=cards
install:
  - travis_retry pip install -r requirements.txt
  # - ./setup_spellfix.sh
script:
  - python dev.py tests -m "not tappedout"
  - python dev.py mypy
  - isort --check-only
notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never
