language: python
branches:
  except:
    - staging.tmp
    - trying.tmp
python:
  - "3.8"
cache: pip
services:
  - mysql
env:
  global:
    - mysql_user=root slow_query=999.0
before_install:
  - nvm install 12
install:
  - travis_retry pipenv sync
  - npm install
  - npm run-script build
  - echo "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));" | mysql
script:
  - pipenv run python dev.py tests
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
