language: python
python:
  - "3.5"
services:
  - mysql
env:
  - mysql_user=root magic_database=cards.sqlite
  - mysql_user=root magic_database=cards
install:
  - pip install -r requirements.txt
  - ./setup_spellfix.sh
  - python run.py maintenance reprime_cache
script:
  - pytest
  # - mypy --ignore-missing-imports .
