name: Run Tests
on: ['push', 'pull_request']

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9
        cache: 'pipenv'
    - uses: PennyDreadfulMTG/setup-linters@main
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv wheel
        if [ -f Pipfile ]; then pipenv sync --dev; fi
    - name: Run mypy
      run: pipenv run python dev.py mypy
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9
        cache: 'pipenv'
    - uses: PennyDreadfulMTG/setup-linters@main
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv wheel pydantic
        if [ -f Pipfile ]; then pipenv sync --dev; fi
    - name: Run flake8
      run: pipenv run python dev.py lint

  test:
    name: test
    runs-on: ubuntu-latest
    env:
      mysql_user: root
      mysql_passwd: bad-password
      mysql_host: 127.0.0.1

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9
        cache: 'pipenv'
    - uses: getong/mariadb-action@v1.1
      with:
        mysql root password: bad-password
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv wheel
        if [ -f Pipfile ]; then pipenv sync --dev; fi
    - uses: PennyDreadfulMTG/setup-linters@main
    - name: Run pytest
      run: |
        pipenv run pytest
        pipenv run python dev.py upload-coverage
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/TestResults.xml'

  jslint:
    name: jslint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9
        cache: 'pipenv'
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv wheel
        python build.py
    - name: Run jslint
      run: pipenv run python dev.py jslint
